### ISSUE TITLE
game doesnt start when I enter a nickname 

### ISSUE THREAD

**Issue by Ice-wiz** [honeydreamssoftwares/simple_chess#17]
Instead of starting the game  , it takes me to a page with some random move history 
![issue image](https://github.com/honeydreamssoftwares/simple_chess/assets/155053352/efaa12f2-ce1e-435a-a91d-00361a98673d)

**Comment by honeydreamssoftwares** [comment]
seems its joining old session. Let me clear the session for now. Later I will make a fix.

Cleared the session, you can do fresh testing.

**Comment by Ice-wiz** [comment]
yes , its fixed now , Can use please mention how did you clear the session and why is it a temporary fix and what should be a better fix for this ?

**Comment by honeydreamssoftwares** [comment]
Just go to https://chessbackend.askzombi.com/colyseus/ and 'dispose'. It should be a authenticated endpoint but the game is in testing so anyone can access now.

**Comment by honeydreamssoftwares** [comment]
Currently it's a 'create or join room' call that's causing issues. Planning to make it just create and join another player with a invite. Also ending the game should destroy the room after a timeout will fix the issue of stale states.
