### ISSUE TITLE
UI not rendering well , when I enter a game

### ISSUE THREAD

**Issue by Ice-wiz** [honeydreamssoftwares/simple_chess#18]
![image](https://github.com/honeydreamssoftwares/simple_chess/assets/155053352/27a199ea-b339-438f-b963-e4313ce045ca)

**Comment by honeydreamssoftwares** [comment]
What is the browser and OS?

**Comment by Ice-wiz** [comment]
yes , this seems specific for Firefox (windows) , working fine on chrome

**Comment by honeydreamssoftwares** [comment]
ok, i will test on firefox as well, should be fixed with some tailwind layout.

**Comment by honeydreamssoftwares** [comment]
https://github.com/honeydreamssoftwares/simple_chess/pull/23  , fixes this issue by changing tailwind classes to grid.
