### ISSUE TITLE
problems starting the game with bot after ending a game with user 

### ISSUE THREAD

**Issue by Ice-wiz** [honeydreamssoftwares/simple_chess#19]
When I finish/end a game with user and start a new bot game in the same session , it doesn't work who its supposed to be 

![image](https://github.com/honeydreamssoftwares/simple_chess/assets/155053352/70d7cf13-d9fc-4b97-852d-ba78b1181855)

**Comment by honeydreamssoftwares** [comment]
Good catch, I will fix it. Seems states are not syncing well between client and server.

**Comment by honeydreamssoftwares** [comment]
Fixed with PR https://github.com/honeydreamssoftwares/simple_chess/pull/20

**Comment by honeydreamssoftwares** [comment]
The initial states were not resetting on new game. adding initial states to join call fixed the issue see. https://github.com/honeydreamssoftwares/simple_chess/pull/21
